/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spidergui;

import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import spidercore.SpiderLogic;

/**
 *
 * @author gdrodriguez
 */
public class SpiderFrame extends javax.swing.JFrame {
    
    // Configuración de preferencias
    private final Preferences configPref = Preferences.userRoot().node(this.getClass().getName());
    private final static String CFG_001 = "iteraciones";
    private final static String CFG_002 = "ruta_descarga";
    
    // Singleton de clase
    private static SpiderFrame instance = null;

    /**
     * Creates new form NewJFrame
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    protected SpiderFrame() {
        // Init GUI
        initComponents();
        // Required 'cause the setLocation method is regenerated by code below
        this.setLocationRelativeTo(null);
        // Load last properties
        loadLastPreferences();
    }
    
    /**
     * Método que permite obtener una única instancia del frame principal allí dónde 
     * se necesite, sin crear nuevas instancias del mismo. AKA Singleton.
     * @return instancia de SpiderFrame única.
     */
    public static SpiderFrame getInstance() {
        if (instance == null) {
            instance = new SpiderFrame();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiConfigFileChooser = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        guiMainStart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        guiConfigDepthL = new javax.swing.JLabel();
        guiConfigDepth = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        guiConfigApply = new javax.swing.JButton();
        guiConfigDeshacer = new javax.swing.JButton();
        guiConfigPathL = new javax.swing.JLabel();
        guiConfigPath = new javax.swing.JTextField();
        guiConfigPathB = new javax.swing.JButton();

        guiConfigFileChooser.setDialogTitle("Elija el directorio de descarga de torrents");
        guiConfigFileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 300));
        setResizable(false);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        guiMainStart.setText("Iniciar");
        guiMainStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiMainStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(guiMainStart, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guiMainStart)
                .addGap(84, 84, 84))
        );

        jTabbedPane1.addTab("Principal", jPanel1);

        guiConfigDepthL.setText("Iteraciones");

        guiConfigDepth.setColumns(5);
        guiConfigDepth.setToolTipText("Indica la cantidad de iteraciones que se realizarán contra la web");

        guiConfigApply.setText("Guardar");
        guiConfigApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiConfigApplyActionPerformed(evt);
            }
        });

        guiConfigDeshacer.setText("Deshacer");

        guiConfigPathL.setText("Ruta de descarga");

        guiConfigPathB.setText("Buscar");
        guiConfigPathB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiConfigPathBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(guiConfigApply)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guiConfigDeshacer))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guiConfigPathL)
                                    .addComponent(guiConfigDepthL))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guiConfigDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guiConfigPath, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiConfigPathB)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guiConfigDepthL)
                    .addComponent(guiConfigDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guiConfigPathL)
                    .addComponent(guiConfigPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guiConfigPathB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guiConfigApply)
                    .addComponent(guiConfigDeshacer))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Configuración", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guiMainStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiMainStartActionPerformed
        if ( ( guiConfigDepth.getText().length() > 0 ) && ( getGuiConfigPath().getText().length() > 0 ) ) {
            //System.out.println(guiConfigDepth.getText());
            SpiderLogic logic = new SpiderLogic();
            logic.execute(Integer.parseInt(guiConfigDepth.getText()));
        } else {
            JOptionPane.showMessageDialog(null, "Asegúrese de que todos los campos "
                    + "están informados en la pestaña de Configuración", "Error", JOptionPane.ERROR_MESSAGE);
            guiMainStart.setEnabled(false);
        }
    }//GEN-LAST:event_guiMainStartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void guiConfigApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiConfigApplyActionPerformed
        saveConfigProperties();
    }//GEN-LAST:event_guiConfigApplyActionPerformed

    private void guiConfigPathBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiConfigPathBActionPerformed
        // From https://netbeans.org/kb/docs/java/gui-filechooser.html
        if (guiConfigFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            getGuiConfigPath().setText(guiConfigFileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_guiConfigPathBActionPerformed

    /**
     * Habilita nuevamente el botón de Inicio. Normalmente este botón se deshabilita
     * ante un error de configuración.
     * @param evt Evento de usuario en GUI
     */
    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        guiMainStart.setEnabled(true);
    }//GEN-LAST:event_jTabbedPane1StateChanged

    /**
     * @return the guiConfigPath
     */
    public javax.swing.JTextField getGuiConfigPath() {
        return guiConfigPath;
    }

    /**
     * @param guiConfigPath the guiConfigPath to set
     */
    public void setGuiConfigPath(javax.swing.JTextField guiConfigPath) {
        this.guiConfigPath = guiConfigPath;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpiderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpiderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpiderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpiderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                getInstance().setVisible(true);
                //new SpiderFrame().setVisible(true);
            }
        });
    }
    
    /**
     * Método que carga, al iniciar, las preferencias de usuario. En Windows se almacenan
     * en el registro en HKEY_LOCAL_MACHINE\Software\JavaSoft\Prefs\Nombre-de-clase.
     * Configura a partir de él la propiedad iteraciones y la carga en la pestaña
     * de configuración.
     */
    private void loadLastPreferences () {
        if (configPref != null) {
            // Obtiene las preferencias guardadas, en caso contrario establece un valor por defecto
            guiConfigDepth.setText(configPref.get(CFG_001, "5"));
            guiConfigPath.setText(configPref.get(CFG_002, ""));
            System.out.println("Cargadas preferencias de usuario de: " + configPref.absolutePath());
        } else {
            JOptionPane.showMessageDialog(null, "Error al crear clave de preferencias, "
                    + "no se guardará la configuración", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    /**
     * Método que guarda los valores de configuración en la clave 
     * HKEY_LOCAL_MACHINE\Software\JavaSoft\Prefs\Nombre-de-clase (En Windows).
     */
    private void saveConfigProperties () {
        if (configPref != null) {
            configPref.put(CFG_001, guiConfigDepth.getText());
            configPref.put(CFG_002, guiConfigPath.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Error al crear clave de preferencias, "
                    + "no se guardará la configuración", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guiConfigApply;
    private javax.swing.JTextField guiConfigDepth;
    private javax.swing.JLabel guiConfigDepthL;
    private javax.swing.JButton guiConfigDeshacer;
    private javax.swing.JFileChooser guiConfigFileChooser;
    private javax.swing.JTextField guiConfigPath;
    private javax.swing.JButton guiConfigPathB;
    private javax.swing.JLabel guiConfigPathL;
    private javax.swing.JButton guiMainStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
